config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get  'contacts/new', to: 'contacts#new'
  post 'contacts/new', to: 'contacts#create'
  root 'static_pages#top'
  get 'static_pages/portfolio'
  get 'static_pages/career'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

class Contact < ApplicationRecord
  validates :name, presence: { message: '名前を入力してください' }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: { message: 'メールアドレスを入力してください' }, format: { with: VALID_EMAIL_REGEX }
  validates :message, presence: { message: 'お問い合わせ内容を記載して下さい' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_email(@contact).deliver
      flash[:success] = 'お問い合わせを受け付けました'
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def top; end

  def portfolio; end

  def career; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/new.html.erb
<div class="center">
  <h1>お問い合わせ</h1>
  <%= form_for(@contact, url: contacts_new_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div>
      <%= f.label :name, 'お名前'%>
    </div>
    <div>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email, 'メールアドレス'%>
    </div>
    <div>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.label :message, 'お問い合わせ内容'%>
    </div>
    <div>
      <%= f.text_area :message %>
    </div>
    <div>
      <%= f.submit "送信" %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-center">
  <p>Copyright &copy;2020 Kazuho Shibuya, All Rights Reserved.</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body id="wrapper">
    <main>
      <% if flash[:success] %>
        <div class="flash">
          <%= flash[:success] %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-danger">
      <%= t('.errors count', errors_count: object.errors.count) %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/career.html.erb
<h1>CAREER</h1>
<div class="row">
  <div class="year">
    <p>2017</p>
  </div>
  <div class="content">
    <p>新卒で情報システムサービス会社に入社。自社で半年間の研修を実施。</p>
    <p>研修では、最初の３ヶ月で700ステップほどの社員管理システムを作成。使用技術：Java、MYSQL、JSP、Tomcat、Eclipse</p>
    <p>機能設計書の作成、コーディング、単体テスト仕様書の作成、テストの実施まで行った。</p>
    <p>基本的なSQLの構文（INSERT、UPDATE、DELETE、SELECT）、JSP⇄Java⇄DBのサーブレットの一連の流れなどを学んだ。</p>
    <p>次の３ヶ月で、2000ステップほどの図書管理システムを作成。使用技術：Java、MYSQL、JSP、Tomcat、Eclipse</p>
    <p>オブジェクト指向言語特有の動きを学ぶため、チェック処理の共通化を実施した。</p>
    <p>研修期間終了後、大手通信系グループ会社に常駐。BtoB物流管理システムの改修、運用保守を１年半経験。 使用技術：Java、PL/SQL、Linux、Oracle9i、Jsp、Weblogic、Eclipse</p>
    <p>運用保守作業では、Linuxのコマンドを理解し、クーロンの設定作業などを行った。本番環境でコマンドを打つときの緊張感、ダブルチェックの重要性などを学んだ。</p>
    <p>改修作業では、機能設計書の修正からテストの実施までを担当した。改修箇所が軽微な場合でも、影響箇所が多岐に渡る場合もあることを身をもって経験した。</p>
  </div>
</div>
<div class="row">
  <div class="year">
    <p>2019</p>
  </div>
  <div class="content">
    <p>大手保険会社に常駐。社内システムの改修を半年経験。 使用技術：CRS(Biz/Browser専用のスクリプト言語)</p>
    <p>同会社で社内業務のPRA開発を１年３ヶ月経験。使用技術：VB.net、Uipath</p>
  </div>
</div>

app/views/static_pages/portfolio.html.erb
<div>
  <h1>PORTFOLIO</h1>
  <%= link_to 'Unknown Music', 'https://www.unknownmusic.net'%>
  <p>音楽試聴アプリです</p>
  <%= link_to 'Github', 'https://github.com/Kazuho-Shibuya'%>
  <h2>機能一覧</h2>
  <p>・簡単ログイン機能</p>
  <p>・管理ユーザー機能(ユーザーを削除)</p>
  <p>・ユーザー登録、削除、編集、検索機能</p>
  <p>・ユーザー認証機能</p>
  <p>・パスワードリセット機能</p>
  <p>・ユーザーログイン、ログアウト機能</p>
  <p>・ユーザ一覧機能</p>
  <p>・いいね機能(Ajax)</p>
  <p>・人気投稿機能</p>
  <p>・投稿検索機能</p>
  <p>・フォロー機能</p>
  <p>・音楽検索機能</p>
  <p>・音楽投稿、削除機能</p>
  <p>・ページネーション機能</p>
  <h2>使用技術</h2>
  <h3>インフラ</h3>
  <p>・AWS</p>
  <p>・Docker/docker-compose</p>
  <h3>フロントエンド</h3>
  <p>・HTML</p>
  <p>・CSS</p>
  <h3>バックエンド</h3>
  <p>・Ruby 2.5.0</p>
  <p>・Ruby on Rails 5.2.4.2</p>
  <h3>外部API</h3>
  <p>・Spotify API</p>
  <h3>テスト</h3>
  <p>・RSpec</p>
  <h4>参考文献</h4>
  <p>・Progate Ruby</p>
  <p>・Progate Ruby on Rails5</p>
  <p>・Railsチュートリアル</p>
  <p>・Ruby on Rails 5 速習実践ガイド</p>
  <p>・Progate HTML&CSS</p>
  <p>・Progate JavaScript</p>
  <p>・Progate Command Line</p>
  <p>・Progate Git</p>
  <p>・わかばちゃんと学ぶGit使い方入門</p>
  <p>・Udemy 初めてのGitとGitHubの学習ログ</p>
  <p>・GitHub Learning Lab</p>
  <p>・everydayrails RSpecによるRailsテスト入門</p>
  <p>・Amazon Web Services 基礎からのネットワーク＆サーバー構築 改訂版</p>
  <p>・ゼロからわかるAmazon Web Services超入門</p>
  <p>・入門docker</p>
  <p>・Docker/Kubernetes 実践コンテナ開発入門</p>
</div>

app/views/static_pages/top.html.erb
<div class="center">
  <h1>Kazuho Shibuya</h1>
  <h3>Backend engineer</h3>
  <%= link_to 'PORTFOLIO', static_pages_portfolio_path, class: 'link-style' %>
  <%= link_to 'CAREER', static_pages_career_path, class: 'link-style' %>
  <%= link_to 'CONTACT', contacts_new_path, class: 'link-style' %>
  <h2>Keep and Challenge</h2>
</div>